"""add metadata and path

Revision ID: d65c602a7b0d
Revises: 60a34b464052
Create Date: 2026-09-15 00:03:00.488233

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd65c602a7b0d'
down_revision: Union[str, Sequence[str], None] = '60a34b464052'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('storage_path', sa.String(length=500), nullable=False))
    op.add_column('documents', sa.Column('doc_metadata', sa.JSON(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'doc_metadata')
    op.drop_column('documents', 'storage_path')
    # ### end Alembic commands ###
